In [1]:
import csv
from datetime import datetime
from datetime import date
from email.message import EmailMessage
import numpy as np
import os
import pandas as pd
import re
import smtplib
import xlrd

In [2]:
# read csv file into Pandas dataframe

filename = 'testlist2.csv'

cols = [
    'timestamp',
    'venue',
    'streetaddy',
    'cityaddy',
    'phone',
    'karaoke',
    'karadays',
    'karastart',
    'karaend',
    'performer_1',
    'genre_1',
    'date_1',
    'start_1',
    'end_1',
    'cost',
    'photo',
    'performer_2',
    'genre_2',
    'date_2',
    'start_2',
    'performer_3',
    'genre_3',
    'date_3',
    'start_3',
    'performer_4',
    'genre_4',
    'date_4',
    'start_4',
    'performer_5',
    'genre_5',
    'date_5',
    'start_5',
    'performer_6',
    'genre_6',
    'date_6',
    'start_6',
    'performer_7',
    'genre_7',
    'date_7',
    'start_7'
]

df = pd.read_csv(filename,
                 usecols=[0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                          15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
                          25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
                          35, 36, 37, 38, 39, 40, 41,42],
                 names=cols,
                 dtype=object,
                 encoding="ISO-8859-1")
df = df.drop(df.index[0])

In [10]:
# Print values to text file
venue = df.venue
base_filename = 'Values.txt'
dfp = pd.DataFrame()
with open(os.path.join('/Users/rayd/workspace/clublistings', base_filename),'w') as outfile:
    venue.to_string(outfile)

In [5]:
venue = df.venue

base_filename = 'Values.txt'
dfp = pd.DataFrame()
with open(os.path.join('/Users/rayd/workspace/clublistings', base_filename),'w') as outfile:
    venue.to_string(outfile)

/Users/rayd/workspace/clublistings

In [8]:
df.venue = df.venue.str.upper()
df.streetaddy = df.streetaddy.str.replace('Rd', 'Road')
df.phone = df.phone.str.replace(r'1([0-9]{3})([0-9]{3})([0-9]{4})$' ,
                              r'\1-\2-\3', regex=True) #like 13523745035
df.phone = df.phone.str.replace(r'/^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/',
                              r'\1-\2-\3', regex=True) #like (352) 374-5035
#df.cityaddy = df.cityaddy.str()

df.head()

,timestamp,venue,streetaddy,cityaddy,phone,karaoke,karadays,karastart,karaend,performer_1,...,date_5,start_5,performer_6,genre_6,date_6,start_6,performer_7,genre_7,date_7,start_7
1,2019/03/04 8:44:24 AM EST,THE CORKSCREW,16 SW Broadway St,Ocala,352-402-0158,"Performance (individual, duet or band)",NaN,19:00,22:00,Charlie and Stephanie Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019/03/05 9:46:50 AM EST,GOOD TIME BAR & GRILL,8921 E. Hwy 25,Belleview,352-203-5445,Karaoke,NaN,21:00,01:00,Good 2 Go,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019/03/05 10:49:38 AM EST,OCALA NEWSROOM,2121 SW 19th Ave. Road,Ocala,352-867-4120,Yes,Monday;Tuesday;Wednesday;Thursday,21:00,00:00,Youngblood's Ragtime Band,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Only keep rows with timestamp in the past week

In [ ]:
def listing_pn(df):
    
    """Function to take venue info and convert
    to narrative."""
    
    global pn

    pn += '\n' + ': ' + streetaddy + ',' + cityaddy + '; '
    
    base_filename = 'Values.txt'
    dfp = pd.DataFrame(df)
    with open(os.path.join('/Users/rayd/workspace/clublistings', base_filename),'w') as outfile:
    df.to_string(outfile)
    return(pn)

In [ ]:
def get_timestamp(time_object=None):
    if not time_object


pd.to_datetime(df.karastart[1]).strftime('%I:%M:%S')

In [ ]:
def karaoke_pn(df):
    
    """Function to take performance 1 and convert to
    a print narrative"""
    
    global pn
    
    if "Yes" in df.karaoke:
        df.karadays = df.karadays.str.replace(';', ',')
        df.karadays = df.karadays.str.replace('Monday', 'Mon.')
        df.karadays = df.karadays.str.replace('Tuesday', 'Tue.')
        df.karadays = df.karadays.str.replace('Wednesday', 'Wed.')
        df.karadays = df.karadays.str.replace('Thursday', 'Thur.')
        df.karadays = df.karadays.str.replace('Friday', 'Fri.')
        df.karadays = df.karadays.str.replace('Saturday', 'Sat.')
        df.karadays = df.karadays.str.replace('Sunday', 'Sun.')
        karadays = df.karadays.astype('|S80')

In [ ]:
"""Function to take performance 1 and convert to
a print narrative"""

In [ ]:
"""Main function, iterating through rows and calling
the helper functions."""

if "__name__" == "__main__":
    for row in df.iterrows():
        # The new listings and, later, its path:
        path_directory = os.path.dirname(os.path.abspath(__file__))
        listings = os.path.join(path_directory, 'golistings.txt')
        # Delete old report file since we'll be building a new one here.
        if os.path.exists(listings):
            os.remove(listings)
        else:
            print(f"The old file for {listings} isn't there.")
        
        pn = ""
        venue_pn(df)
        f=open(listings,"a")
        f.write(pn)
        f.close()